"""Author-owned original practice material; rerun only when building the initial pack."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SETS=[]
def add(part,title,genre,speakers,turns,qs,expressions):
 n=1+sum(s['part']==part for s in SETS); sid=f'P{part}-{n:04d}'
 SETS.append(dict(id=sid,part=part,packId=f'part{part}-pack01',title=title,difficulty='standard',genre=genre,audio=f'audio/part{part}/{sid.lower()}.mp3',speakers=[dict(id=k,label=label,voice=voice) for k,label,voice in speakers],transcript=[dict(speaker=k,text=en,translation=ja) for k,en,ja in turns],questions=[dict(id=f'{sid}-Q{i+1}',text=q,options=o,answer=a,explanation=e) for i,(q,o,a,e) in enumerate(qs)],expressions=[dict(english=e,japanese=j) for e,j in expressions]))
M=('M','Man','en-US-GuyNeural'); W=('W','Woman','en-US-AriaNeural'); M2=('M2','Man 2','en-GB-RyanNeural'); W2=('W2','Woman 2','en-GB-SoniaNeural')
add(3,'A delivery before the opening','店舗・配送',[M,W],[
('W',"Hi, Daniel. The display tables for our new shop were supposed to arrive this morning, but the tracking page now says Thursday. We open on Wednesday. Have you heard from the supplier?",'ダニエル、新店舗の展示台は今朝届く予定だったのに、追跡ページでは木曜になっているの。開店は水曜よ。納入業者から連絡はあった？'),
('M',"Yes. Their truck broke down. They can send half the order tomorrow with another carrier, but there's an extra delivery charge.",'あったよ。トラックが故障したそうだ。別の配送会社なら半分を明日送れるけど、追加料金がかかる。'),
('W',"Half would be enough for the front window. Could we borrow the folding tables from our other branch for the rest?",'半分あれば正面のウインドーには足りるわ。残りは別の支店から折りたたみ式の台を借りられるかしら？'),
('M',"Good idea. I'll ask their manager. Can you approve the additional charge so I can confirm the shipment?",'いいね。支店長に聞いてみる。配送を確定できるよう、追加料金を承認してくれる？'),
('W',"Of course. Send me the amount first. I'll update the window plan while you make that call.",'もちろん。先に金額を送って。あなたが電話している間に、展示計画を直しておくわ。')],[
('What problem are the speakers discussing?',['A shop has lost its lease.','Some furniture will arrive late.','A window needs to be repaired.','A branch has ordered too many tables.'],1,'配送予定が木曜に変わった一方、開店は水曜。展示台の到着遅延が問題。'),
('Why does the woman mention the other branch?',['To suggest a temporary solution','To recommend a new supplier','To explain a delivery address','To request a permanent transfer'],0,'他支店の折りたたみ台を借り、開店時に足りない台を補う提案。'),
('What will the man most likely do next?',['Redesign a display','Cancel the entire order','Call another store manager','Repair a delivery truck'],2,'男性は別支店の責任者に台を借りられるか確認すると述べている。')],[('be supposed to','〜する予定である'),('an additional charge','追加料金')])
add(3,'Moving a workshop','会議・予約',[W,W2],[
('W',"Sophie, we have thirty-two registrations for Friday's workshop now. The small training room only seats twenty-four. Is the larger room available?",'ソフィー、金曜の研修の申込者が32人になったの。小研修室は24席しかないわ。大きい部屋は空いている？'),
('W2',"The sales team has booked it until eleven. Your workshop starts at ten, doesn't it? We could use the conference center across the street, though it would cost more.",'営業部が11時まで予約しているわ。研修は10時開始よね？ 通りの向かいの会議施設も使えるけど、費用が増えるわ。'),
('W',"I'd rather stay here. Our guest speaker doesn't arrive until eleven thirty anyway. The first hour was just going to be introductions.",'ここで開催したいわ。ゲスト講師が来るのも11時半だし、最初の1時間は自己紹介だけの予定だったから。'),
('W2',"Then why not start at eleven fifteen? That gives us fifteen minutes to rearrange the chairs. I can reserve the room from eleven.",'それなら11時15分開始はどう？ 椅子を並べ替える時間が15分あるわ。11時から予約しておくね。'),
('W',"That works. I'll email everyone the new start time and ask the catering company to deliver lunch half an hour later.",'それでいいわ。全員に開始時間の変更をメールして、仕出し業者には昼食を30分遅く届けてもらうね。')],[
('Why do the speakers need a different room?',['The equipment is broken.','A speaker requested a stage.','More people have registered than expected.','The original room is being painted.'],2,'申込者32人に対し元の部屋は24席なので、より広い部屋が必要。'),
('What does the first woman mean when she says, "I’d rather stay here"?',['She prefers not to rent an outside venue.','She wants to remain at her desk.','She cannot attend the workshop.','She plans to move her office.'],0,'外部会議施設の提案に対し、自社内で開催したい意向を示している。'),
('What time will the workshop begin?',['10:00','11:00','11:15','11:30'],2,'11時15分開始の提案に That works と同意。11時は会場予約開始、11時半は講師到着。')],[('rearrange the chairs','椅子を並べ替える'),('That works.','それで大丈夫です。')])
add(3,'A revised product photograph','広告・制作',[M,M2],[
('M',"Oliver, have you seen the draft for the new backpack advertisement? The headline looks great, but the photograph still shows last year's model.",'オリバー、新しいリュックの広告案を見た？ 見出しはいいけど、写真がまだ去年のモデルだよ。'),
('M2',"Really? I used the folder the product team shared on Monday. I thought those were the approved images.",'そうなの？ 商品部が月曜に共有したフォルダーを使ったんだ。承認済みの写真だと思っていたよ。'),
('M',"They added a new folder yesterday. The current model has a side pocket for a water bottle. That's actually the main feature we're promoting.",'昨日新しいフォルダーが追加されたんだ。現行モデルには水筒用のサイドポケットがある。それが今回の主な訴求点なんだよ。'),
('M2',"I see. I'll replace the photo. Do we still need to send the final version to the magazine by noon?",'わかった。写真を差し替えるよ。雑誌社への最終版送付は、やっぱり正午まで？'),
('M',"They've given us until three, but I'd like to review it at two. Please keep the headline as it is and make sure the pocket is clearly visible.",'3時まで延ばしてくれたけど、2時には確認したい。見出しはそのままにして、ポケットがはっきり見えるようにしてね。')],[
('What needs to be changed in the advertisement?',['The product name','The headline','The photograph','The magazine logo'],2,'去年のモデルが写っているため、写真の差し替えが必要。'),
('What feature is being emphasized?',['A lower price','A pocket for a bottle','A wider shoulder strap','A longer warranty'],1,'水筒用サイドポケットを main feature と説明している。'),
('When does the first man want to review the revision?',['At noon','At one o’clock','At two o’clock','At three o’clock'],2,'雑誌社の締切は3時だが、男性が確認したいのは2時。')],[('the final version','最終版'),('as it is','そのままで')])
add(3,'A demonstration without a network','展示会・技術',[W,M,W2],[
('W',"Before the visitors arrive, let's check the demonstration. Eric, is the inventory app running on the tablet?",'来場者が来る前にデモを確認しましょう。エリック、タブレットで在庫管理アプリは動いている？'),
('M',"The app is fine, but the wireless network keeps disconnecting. If that happens during the live search, the screen will freeze.",'アプリは大丈夫ですが、無線ネットワークが何度も切れます。検索の実演中に切れると画面が止まってしまいます。'),
('W2',"I saved a sample database on the tablet yesterday. We can demonstrate the search without connecting to the server. The numbers won't be current, though.",'昨日サンプルのデータベースをタブレットに保存しました。サーバーにつながなくても検索を実演できます。ただし数値は最新ではありません。'),
('W',"That's fine as long as we explain that it's sample data. Eric, switch to that version. Nina, could you put a small note beside the tablet?",'サンプルデータだと説明すれば大丈夫です。エリック、その版に切り替えて。ニナ、タブレットの横に小さな注意書きを置いてくれる？'),
('M',"Sure. It loads much faster this way, too. We should be ready in five minutes.",'はい。この方法だと読み込みもずっと速いです。5分で準備できそうです。'),
('W2',"I'll print the note now. I'll also bring a spare charging cable from the office.",'今、注意書きを印刷します。オフィスから予備の充電ケーブルも持ってきます。')],[
('What are the speakers preparing for?',['A software demonstration','A staff interview','A warehouse delivery','A network maintenance course'],0,'来場者に在庫管理アプリを見せるデモの準備。'),
('How will they address the connection problem?',['By delaying the visitors','By moving to another office','By using locally saved data','By replacing the tablet'],2,'タブレット内に保存したサンプルデータを使い、接続なしで実演する。'),
('What is Nina asked to do?',['Update the inventory figures','Prepare a notice','Repair the wireless router','Lead a five-minute meeting'],1,'Nina, could you put a small note... が依頼。充電ケーブルは本人が追加で提案した行動。')],[('as long as','〜する限り／〜という条件なら'),('a spare charging cable','予備の充電ケーブル')])
add(3,'Choosing a train after a meeting','出張・交通',[M,W],[
('M',"Our client meeting in Westport has been moved to Thursday afternoon. I was going to drive, but the hotel charges quite a lot for overnight parking.",'ウェストポートでの顧客との会議が木曜午後に変わったんだ。車で行くつもりだったけど、ホテルの一晩の駐車料金がかなり高いんだよ。'),
('W',"Why don't we take the train? There's one at eight forty that gets in just before eleven. The client's office is a short walk from the station.",'電車にしない？ 8時40分発で11時少し前に着く便があるわ。顧客のオフィスは駅から歩いてすぐよ。'),
('M',"That sounds better. Can we get a flexible return ticket? Last time the discussion ran an hour longer than planned.",'その方がいいね。帰りは変更できる切符にできるかな？ 前回は話し合いが予定より1時間長引いたから。'),
('W',"Yes, but it's cheaper if we book today. I'll check whether our travel account covers the flexible fare.",'できるけど、今日予約すると安いの。会社の出張用アカウントで変更可能な運賃を購入できるか確認するね。'),
('M',"Thanks. Once you know, send me the total. I'll ask our supervisor to approve it before the end of the day.",'ありがとう。わかったら合計金額を送って。今日中に上司に承認してもらうよ。')],[
('Why does the man reconsider driving?',['The roads will be closed.','His car needs repairs.','The parking fee is high.','He has lost his license.'],2,'ホテルの一晩の駐車料金が高いことが理由。'),
('What concern does the man express about the return trip?',['The meeting may finish late.','The last train is fully booked.','The station is difficult to find.','The client will need a ride.'],0,'前回の話し合いが1時間長引いたため、変更可能な帰りの切符を希望。'),
('What will the woman check?',['Whether a hotel room is available','Whether a fare can be purchased through their account','Whether the client can meet on Wednesday','Whether a supervisor can join the trip'],1,'travel account covers the flexible fare の確認をすると述べている。')],[('run longer than planned','予定より長引く'),('a flexible return ticket','変更可能な帰りの切符')])
add(3,'Changing a lunch order','飲食・社内行事',[W,M,M2],[
('W',"I've just received the lunch order for tomorrow's orientation. There are eighteen sandwiches, but four of our new employees requested vegetarian meals.",'明日の新人研修用ランチの注文内容が届きました。サンドイッチは18個ですが、新入社員4人がベジタリアン用を希望しています。'),
('M',"I put that in the online form. Does the confirmation list the fillings?",'オンラインフォームに入力しましたよ。確認書に具材は載っていますか？'),
('W',"It only says assorted sandwiches. I don't want to find out tomorrow that they're all chicken or tuna.",'サンドイッチ各種、としか書かれていません。明日になって全部チキンやツナだったとわかるのは困ります。'),
('M2',"I know the bakery owner. I'll call and confirm that four are vegetarian. Should I also ask them to label the boxes individually?",'私はパン屋のオーナーを知っています。電話して4個がベジタリアン用か確認します。箱ごとにラベルを付けてもらうようにも頼みましょうか？'),
('W',"Yes, please. And delivery should be to the reception desk, not the training room. The room will be locked until ten thirty.",'お願いします。それと配達先は研修室ではなく受付です。部屋は10時半まで施錠されています。'),
('M',"I'll let reception know. We have enough drinks already, so there's no need to add any to the order.",'受付に伝えておきます。飲み物は十分あるので、注文への追加は不要です。')],[
('What is unclear about the order?',['Whether drinks are included','What kinds of sandwiches will be provided','How many employees will attend','Which day the food will arrive'],1,'確認書に具材の詳細がなく、ベジタリアン用が入っているか不明。'),
('What does the second man offer to do?',['Unlock the training room','Collect the food himself','Contact the bakery','Buy additional drinks'],2,'パン屋のオーナーを知る2人目の男性が、電話で確認すると申し出る。'),
('Where should the food be delivered?',['To the reception desk','To the training room','To the staff kitchen','To the bakery entrance'],0,'配達先は受付と明言。研修室は10時半まで施錠されている。')],[('assorted sandwiches','各種サンドイッチ'),('label individually','個別にラベルを付ける')])
add(4,'A platform change','交通案内',[W],[('W',"Attention, passengers traveling to Brookfield on the nine twenty express. Because of track maintenance near the north entrance, your train will depart from platform six instead of platform two today. The departure time has not changed. Please use the footbridge beside the ticket office to reach platform six; the underground passage is temporarily closed. Passengers who need assistance with luggage or step-free access should speak to a member of staff at the information desk. A connecting shuttle is available for passengers using wheelchairs. Please have your tickets ready before boarding, as tickets cannot be purchased on this service. We apologize for the inconvenience and thank you for your cooperation.",'ブルックフィールド行き9時20分発の急行をご利用のお客様にお知らせします。北側入口付近の線路保守作業のため、本日は2番ホームではなく6番ホームから発車します。発車時刻の変更はありません。地下通路は一時閉鎖中のため、切符売り場の横の歩道橋をご利用ください。荷物の運搬や段差のない経路について支援が必要な方は、案内所の係員にお声がけください。車椅子をご利用のお客様向けに連絡シャトルを用意しています。車内では切符を購入できませんので、乗車前にご用意ください。ご不便をおかけしますが、ご協力をお願いいたします。')],[('Why has the boarding location changed?',['A train arrived late.','A ticket office is moving.','Maintenance work is taking place.','A platform is overcrowded.'],2,'線路の保守作業のためホームを変更。'),('How should most passengers reach the new platform?',['By using a footbridge','By taking an underground passage','By walking through the north entrance','By boarding a shuttle bus'],0,'通常の経路は切符売り場横の歩道橋。シャトルは車椅子利用者向け。'),('What are passengers reminded to do?',['Reserve a seat online','Prepare their tickets before boarding','Change trains at Brookfield','Arrive thirty minutes early'],1,'この列車内では切符を購入できないため、乗車前に用意するよう案内。')],[('step-free access','段差のないアクセス'),('have your tickets ready','切符を用意しておく')])
add(4,'A replacement appliance','留守番電話',[M],[('M',"Hello, Ms. Chen. This is David from Harbor Appliances, calling about the dishwasher you brought in on Monday. Our technician has checked it, and the replacement motor will take three weeks to arrive. Since your machine is still under warranty, we can offer you a new dishwasher of the same model at no charge instead of making you wait for the repair. We have one in our warehouse, and we can deliver it on Friday afternoon. Our driver will also collect the old unit, so please don't bring it back to the shop yourself. If Friday isn't convenient, call me before four tomorrow and we can arrange another date. You can reach me directly at extension two eighteen.",'チェン様、ハーバー家電のデイビッドです。月曜にお持ちいただいた食洗機についてご連絡しました。技術者が確認したところ、交換用モーターの到着には3週間かかります。まだ保証期間内ですので、修理をお待ちいただく代わりに、同じ型の新品を無料でお渡しできます。倉庫に1台あり、金曜午後に配達可能です。配送員が古い本体も回収しますので、ご自身で店にお持ちいただく必要はありません。金曜が不都合な場合は明日の4時までにお電話ください。別の日程を調整します。直通は内線218です。')],[('What is the main purpose of the message?',['To explain a warranty renewal','To offer a replacement product','To announce a store opening','To request a missing payment'],1,'修理部品の納期が長いため、同型の新品への無償交換を提案。'),('Why would a repair take several weeks?',['The technician is on vacation.','The store is being renovated.','A part is not yet available.','The customer has not approved the cost.'],2,'交換用モーターの到着まで3週間かかる。'),('What will the delivery driver do?',['Install a different model','Collect the old dishwasher','Extend the warranty','Take the customer to the shop'],1,'配達時に古い機器も回収すると説明。')],[('under warranty','保証期間内で'),('at no charge','無料で')])
add(4,'A library evening event','施設案内',[W2],[('W2',"Thank you for visiting the River Street Library. A reminder that tonight's talk by travel writer Anna Lewis will begin at six thirty in the second-floor reading room. All reserved seats have now been taken, but we have space for twenty additional guests in the rear seating area. These seats will be offered on a first-come, first-served basis from six o'clock. Please collect a numbered card from the desk near the stairs if you would like one. The talk will last approximately forty minutes, followed by questions and a book signing. Copies of Ms. Lewis's latest book are available at the entrance. The main lending desk will close at its usual time of seven, even though the event continues later.",'リバーストリート図書館にご来館いただきありがとうございます。本日の旅行作家アンナ・ルイス氏の講演は、午後6時半から2階の閲覧室で開催します。予約席は満席ですが、後方席に20名追加でお入りいただけます。こちらは6時から先着順でご案内します。ご希望の方は階段付近のカウンターで番号札をお受け取りください。講演は約40分で、その後に質疑応答とサイン会があります。最新刊は入口で販売しています。催しは7時以降も続きますが、貸出カウンターは通常どおり7時に終了します。')],[('Who is Anna Lewis?',['A librarian','A travel writer','A tour guide','A bookseller'],1,'travel writer と紹介されている。'),('What should people without reservations do?',['Return the following morning','Wait outside the building','Get a numbered card','Buy two copies of a book'],2,'追加の後方席を希望する人は階段付近で番号札を受け取る。'),('What will happen at seven o’clock?',['The lending desk will close.','The talk will begin.','All visitors must leave.','The book signing will end.'],0,'催しの継続にかかわらず、貸出カウンターは通常どおり7時に閉まる。')],[('first-come, first-served','先着順の'),('followed by','その後に〜が続く')])
add(4,'A revised weekly report','社内連絡',[M2],[('M2',"Before we finish today's meeting, I'd like to explain a small change to our weekly sales reports. Starting next Monday, please enter your figures in the shared online form rather than emailing a spreadsheet to me. The form uses the same categories, so you won't need to collect any new information. What is changing is the deadline: submissions are now due at noon on Friday, not at the end of the day. This will give the finance team enough time to review the totals before the weekend. I'll send a link and a short instruction sheet this afternoon. If you can't access the form, contact our IT desk rather than creating your own copy. For this week only, please continue using the old spreadsheet.",'会議を終える前に、週次売上報告の小さな変更について説明します。来週月曜からは、表計算ファイルを私にメールする代わりに、共有オンラインフォームに数値を入力してください。項目は同じなので、新しい情報を集める必要はありません。変更されるのは締切で、金曜の終業時ではなく正午になります。これにより、経理部が週末前に合計を確認できます。本日午後にリンクと簡単な手順書を送ります。フォームにアクセスできない場合は、自分でコピーを作らずIT窓口に連絡してください。今週だけは従来の表計算ファイルを使ってください。')],[('What is the speaker discussing?',['A change in reporting procedures','A reduction in sales targets','A new employee benefit','A schedule for office repairs'],0,'売上報告の提出方法と締切の変更を説明。'),('Why is the deadline being moved?',['To avoid a system upgrade','To allow time for a financial review','To shorten a weekly meeting','To accommodate a customer visit'],1,'経理部が週末前に合計値を確認する時間を確保するため。'),('What should employees do this week?',['Test a new spreadsheet','Submit reports on Monday','Use the existing spreadsheet','Send figures directly to IT'],2,'今週だけは古い表計算ファイルを継続し、変更は来週から。')],[('submissions are due','提出期限は〜である'),('rather than','〜ではなく')])
add(4,'A walking tour in the rain','ツアー案内',[W],[('W',"Good morning, everyone, and welcome to the Old Harbor walking tour. I'm Leah, your guide. The weather forecast now predicts heavy rain around eleven, so we're going to reverse our usual route. We'll visit the outdoor market first while it's still dry, then spend the second half of the tour inside the maritime museum. Your ticket includes museum admission, but it does not include the special photography exhibition on the top floor. Anyone interested in that exhibition can purchase an additional ticket at the museum desk. We'll finish there at twelve fifteen instead of returning to this square. The museum is opposite the central bus stop, and I'll show you where to catch a bus before we go inside. Please stay together as we cross the road.",'オールドハーバーの徒歩ツアーへようこそ。ガイドのリアです。最新の予報では11時ごろに大雨になるので、通常の順路を逆にします。雨が降らないうちに屋外市場を訪れ、後半は海洋博物館の中で過ごします。ツアー券に博物館の入場料は含まれますが、最上階の写真特別展は含まれません。ご希望の方は博物館の窓口で追加券をご購入ください。この広場には戻らず、12時15分に博物館で終了します。博物館は中央バス停の向かいにあり、中へ入る前に乗り場をご案内します。道を渡るときはまとまって移動してください。')],[('Why has the route been changed?',['A market has closed.','Rain is expected later.','A museum is fully booked.','A bus service is suspended.'],1,'11時ごろの大雨の予報を受け、屋外市場を先に訪問する。'),('What requires an extra payment?',['The walking tour map','The regular museum admission','The photography exhibition','The guide’s bus directions'],2,'博物館の通常入場は込みだが、写真特別展は追加券が必要。'),('Where will the tour end?',['At the museum','At the starting square','Inside the market','At the railway station'],0,'博物館で12時15分に終了し、出発した広場には戻らない。')],[('reverse our usual route','通常の順路を逆にする'),('admission','入場／入場料')])
add(4,'A new service for local businesses','広告',[M],[('M',"Are you spending your lunch break waiting to send parcels? Greenway Print and Post now offers a collection service for businesses in the city center. Book a collection before ten in the morning, and our driver will pick up your prepared parcels between two and four that afternoon. There is no collection fee for five or more parcels; smaller collections cost six dollars. You still pay the normal postage for each item. To get started, create a business account on our website and print your shipping labels before the driver arrives. Please note that we cannot collect items weighing more than fifteen kilograms or packages requiring refrigeration. During our first month, new account holders will receive a pack of twenty mailing envelopes at no extra cost. Visit our website for the complete list of eligible streets.",'荷物を送るための待ち時間で昼休みを使っていませんか？ グリーンウェイ・プリント・アンド・ポストでは、市中心部の事業者向け集荷サービスを始めました。午前10時までに予約すると、その日の午後2時から4時の間に配送員が準備済みの荷物を引き取ります。5個以上なら集荷料金は無料、それ未満なら6ドルです。各荷物の通常の送料は別途必要です。まずウェブサイトで事業者アカウントを作り、到着前に配送ラベルを印刷してください。15キロを超える荷物や冷蔵が必要な荷物は集荷できません。初月は新規登録者に発送用封筒20枚を無料で差し上げます。対象の通りの一覧はウェブサイトでご確認ください。')],[('Who is the service intended for?',['Travelers arriving at an airport','Businesses in the city center','Residents outside the city','Refrigerated food suppliers only'],1,'市中心部の事業者向けと明示。'),('When is the collection fee waived?',['When postage is paid in cash','When an account is a year old','When at least five parcels are collected','When a parcel weighs fifteen kilograms'],2,'5個以上で集荷料が無料。送料まで無料になるわけではない。'),('What must customers do before the driver arrives?',['Print shipping labels','Collect free envelopes from a store','Call every recipient','Weigh the delivery vehicle'],0,'事前にアカウントを作成し、配送ラベルを印刷する必要がある。')],[('at no extra cost','追加料金なしで'),('eligible','対象となる／条件を満たす')])
# Balance answer positions across the starter bank (nine A/B/C/D each).
positions=[1,3,0,2,0,2,3,1,2,0,1,3,3,1,2,0,1,0,3,2,2,3,1,0,0,2,1,3,3,0,2,1,1,3,0,2]
for i,q in enumerate(q for s in SETS for q in s['questions']):
 target=positions[i]; old=q['answer']; q['options'][old],q['options'][target]=q['options'][target],q['options'][old];q['answer']=target
for part in (3,4):
 p=ROOT/f'data/part{part}/pack01.json';p.write_text(json.dumps(dict(schemaVersion=1,id=f'part{part}-pack01',sets=[s for s in SETS if s['part']==part]),ensure_ascii=False,indent=2)+'\n')
(ROOT/'data/catalog.json').write_text(json.dumps(dict(schemaVersion=1,packs=[dict(id=f'part{p}-pack01',part=p,title=f'Part {p} · Starter',path=f'data/part{p}/pack01.json',setCount=6,questionCount=18,revision=1) for p in (3,4)]),ensure_ascii=False,indent=2)+'\n')
print(f'{len(SETS)} sets / {sum(len(s["questions"]) for s in SETS)} questions written')
